### ISSUE TITLE
UDP Client

### ISSUE THREAD

**Issue by lemonlambda** [Chalk-Organization/ChalkProtocol#1]
Create UDP client that allows for p2p messaging easily

**Comment by Zephia-Sero** [comment]
Why is this under the `1.0.0` milestone? Surely this should exist during beta/alpha so that it can be properly tested before release.
This issue is pretty vague and I still have doubts about supporting solely UDP. UDP can be lossy, and perhaps TCP would be best to start with, while we are only transmitting/receiving text and files. Later on, UDP can be used for voice and video, since some lossiness is okay there.

**Comment by lemonlambda** [comment]
> Why is this under the `1.0.0` milestone? Surely this should exist during beta/alpha so that it can be properly tested before release.
> This issue is pretty vague and I still have doubts about supporting solely UDP. UDP can be lossy, and perhaps TCP would be best to start with, while we are only transmitting/receiving text and files. Later on, UDP can be used for voice and video, since some lossiness is okay there.

I planned to expand the issue later when I had more time and the 1.0.0 milestone is the first edition of the crate, so I think maybe we should bump this up to a higher version for now. TCP would be a better concern. 

I'll remove the existing UDP code since there is not much, if you haven't removed it already, and I'll create another issue for the TCP.

**Comment by lemonlambda** [comment]
058db3bacac3ed3e9a3b943b1a87b24535881000
